AAR.input_dim: 512

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
CosineLinearWarmupLR.num_warmup_steps: 1000
CosineLinearWarmupLR.num_training_steps: 200000
CosineLinearWarmupLR.scheme: 'lin0' # 'cosine', 'lin', 'lin0', 'exp'
CosineLinearWarmupLR.start_lr_ratio: 0.005
CosineLinearWarmupLR.end_lr_ratio: 0.001

amp: false
val_batch_size: 48
device: cuda
num_iters: 200000
save_iters: [10000, 50000, 100000, 200000]
valid_freq: 1000
sample_freq: 1000
num_workers: 12
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
win_dur: 1

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.3
build_transform.augment:
  - HighPass
  - Smoothing
  - MuLawQuantization
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Data
batch_size: 48
train/AudioDataset.duration: 1.0
train/AudioDataset.n_examples: 10000000

val/AudioDataset.duration: 1.0
val/build_transform.augment_prob: 0.0
val/AudioDataset.n_examples: 250

test/AudioDataset.duration: 1.0
test/build_transform.augment_prob: 0.0
test/AudioDataset.n_examples: 1000

AudioLoader.shuffle: true
AudioDataset.without_replacement: true

train/build_dataset.folders:
  speech_fb:
    - datasets/daps/train
  speech_hq:
    - datasets/vctk
    - datasets/datasets_fullband/vocalset
    - datasets/datasets_fullband/read_speach
    - datasets/datasets_fullband/french_speech
  speech_uq:
    - datasets/datasets_fullband/emotional_speech
    - datasets/common_voice
    - datasets/datasets_fullband/german_speech
    - datasets/datasets_fullband/russian_speech
    - datasets/datasets_fullband/spanish_speech
  music_hq:
    - datasets/musdb/train
  music_uq:
    - datasets/jamendo
  general:
    - datasets/audioset/train

val/build_dataset.folders:
  speech_hq:
    - datasets/daps/val
  music_hq:
    - datasets/musdb/test
  general:
    - datasets/audioset/val

test/build_dataset.folders:
  speech_hq:
    - datasets/daps/test
  music_hq:
    - datasets/musdb/test
  general:
    - datasets/audioset/val